import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/public/LegalPage";

export const metadata: Metadata = { title: "Privacy Policy | BOED LMS", description: "How BOED LMS collects, uses, protects, and manages personal information." };

const sections: LegalSection[] = [
  { title: "Information we collect", paragraphs: ["We collect information you provide when you create an account, enroll in a course, contact us, or use BOED LMS. The information collected depends on how you use the platform."], items: ["Account and profile details, such as your name, email address, phone number, and profile photo.", "Enrollment details and information required by a training provider, which may include date of birth, address, or identification information.", "Learning records, including course progress, attendance, assessment responses, grades, submissions, and certificates.", "Technical information, such as device, browser, IP address, access times, and diagnostic logs.", "Messages and files you submit through platform features or support channels."] },
  { title: "How we use information", paragraphs: ["We process personal information to provide, secure, support, and improve the learning service."], items: ["Create and administer accounts and enrollments.", "Deliver courses, live classes, assessments, results, and certificates.", "Communicate service notices and respond to support requests.", "Protect accounts, prevent abuse, and maintain platform security.", "Analyze service performance and improve accessibility and usability.", "Meet applicable legal, regulatory, and record-keeping obligations."] },
  { title: "How information is shared", paragraphs: ["We do not sell personal information. Information may be shared with the institution delivering your training, authorized instructors and administrators, service providers working on our behalf, or public authorities when legally required."], items: ["Access inside an institution is controlled by role and operational need.", "Service providers are expected to use information only to deliver contracted services.", "Certificate verification displays limited credential information when a valid certificate number is supplied."] },
  { title: "Data security", paragraphs: ["We use administrative, technical, and organizational safeguards intended to protect information from unauthorized access, alteration, disclosure, or loss. No internet service can guarantee absolute security, so you should also protect your password and notify us if you suspect unauthorized account activity."] },
  { title: "Retention", paragraphs: ["We retain information for as long as needed to provide the service, maintain academic and certification records, resolve disputes, enforce agreements, and meet legal obligations. Retention periods may also be set by the institution responsible for your training."] },
  { title: "Your choices and rights", paragraphs: ["Depending on applicable law and your institution’s responsibilities, you may request access to, correction of, or deletion of certain personal information. Some academic, assessment, audit, or certification records may need to be retained."], items: ["Update available profile information from your account settings.", "Contact your institution or BOED LMS to make a privacy request.", "Control optional browser permissions and communication preferences where offered."] },
  { title: "Cookies and local storage", paragraphs: ["BOED LMS uses cookies and similar browser storage for authentication, security, language and theme preferences, and essential product functionality. Blocking essential storage may prevent parts of the service from working correctly."] },
  { title: "Children’s privacy", paragraphs: ["The platform is intended for use through participating training institutions and is not directed to children independently. Where a learner is below the age required to consent under applicable law, the responsible institution must obtain the necessary authorization."] },
  { title: "Policy changes", paragraphs: ["We may update this policy when the service or legal requirements change. The updated date at the top of this page shows when the latest version took effect. Material changes may also be communicated through the platform."] },
  { title: "Contact us", paragraphs: ["For privacy questions or requests, email mailer@boed.org. We may need to confirm your identity before completing a request."] },
];

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" description="This policy explains what information BOED LMS handles and the choices available to you." updated="September 10, 2026" sections={sections} />;
}
