import type {
  AdminExtractedCqPart,
  AdminExtractedQuestion,
  DifficultyValue,
  QuestionTypeValue,
} from "@/lib/admin-assessment-types";

// Local (no-API) heuristic parser: turns OCR/AI question text into structured
// questions. Supports marker blocks, "Question 1" blocks, MCQ options,
// metadata lines, inline marks, and JSON generated by an AI/OCR step.

// CQ (creative question) blocks: a Bengali heading ("সৃজনশীল প্রশ্ন ১" or a
// plain "১." / "1." number), a passage (উদ্দীপক), then four sub-questions
// marked ক./খ./গ./ঘ., each optionally ending with "[N marks]" or "[Marks]".
// The passage often starts on the same line as the heading
// ("সৃজনশীল প্রশ্ন ১ : মেধাবী ছাত্র..."), so the trailing text is captured.
const CQ_HEADING = /^\s*(?:সৃজনশীল\s*প্রশ্ন|CQ|Creative\s*Question)\s*[-.:।]?\s*(\d{1,3}|[০-৯]{1,3})?\s*[:.।]?\s*(.*)$/iu;
const CQ_PART_START = /^\s*([কখগঘ])\s*[.)।:-]\s*(.*)$/u;
const BENGALI_DIGIT_MAP: Record<string, string> = {
  "০": "0", "১": "1", "২": "2", "৩": "3", "৪": "4",
  "৫": "5", "৬": "6", "৭": "7", "৮": "8", "৯": "9",
};

function toArabicDigits(value: string): string {
  return value.replace(/[০-৯]/g, (ch) => BENGALI_DIGIT_MAP[ch] ?? ch);
}

function extractTrailingMarks(text: string): { text: string; marks: number } {
  const match = text.match(MARKS_INLINE) ?? text.match(MARKS_TRAILING);
  if (!match) return { text: text.trim(), marks: 0 };
  const digits = toArabicDigits(match[1] ?? "");
  const marks = Number(digits) || 0;
  return { text: text.replace(match[0], "").trim(), marks };
}

/**
 * Detect and parse CQ blocks (উদ্দীপক + ক/খ/গ/ঘ). Returns null if the text
 * has no CQ part markers, so callers can fall back to the generic parser.
 */
function parseCqBlocks(text: string): AdminExtractedQuestion[] | null {
  const lines = text
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.replace(/ /g, " ").trim())
    .filter(Boolean);

  if (!lines.some((line) => CQ_PART_START.test(line))) return null;

  interface CqBlock {
    passage: string[];
    parts: { label: string; lines: string[] }[];
  }

  const blocks: CqBlock[] = [];
  let current: CqBlock = { passage: [], parts: [] };
  let currentPart: { label: string; lines: string[] } | null = null;
  let started = false;

  const startBlock = () => {
    current = { passage: [], parts: [] };
    currentPart = null;
    started = true;
    blocks.push(current);
  };

  for (const line of lines) {
    const headingMatch = line.match(CQ_HEADING);
    if (headingMatch) {
      startBlock();
      const inlinePassage = (headingMatch[2] ?? "").trim();
      if (inlinePassage) current.passage.push(inlinePassage);
      continue;
    }

    const partMatch = line.match(CQ_PART_START);
    if (partMatch) {
      if (!started) startBlock();
      currentPart = { label: partMatch[1], lines: [partMatch[2]] };
      current.parts.push(currentPart);
      continue;
    }

    if (!started) startBlock();

    if (currentPart) {
      currentPart.lines.push(line);
    } else {
      current.passage.push(line);
    }
  }

  const questions = blocks
    .filter((block) => block.parts.length > 0)
    .map((block): AdminExtractedQuestion => {
      const passage = block.passage.join(" ").replace(/\s+/g, " ").trim();
      const parts: AdminExtractedCqPart[] = block.parts.map((part) => {
        const joined = part.lines.join(" ").replace(/\s+/g, " ").trim();
        const { text: partText, marks } = extractTrailingMarks(joined);
        return { label: part.label, text: partText, marks };
      });
      const totalMarks = parts.reduce((sum, part) => sum + part.marks, 0);
      return {
        type: "WRITTEN",
        question: passage,
        marks: totalMarks,
        options: [],
        correctAnswer: null,
        rubric: null,
        difficulty: "MEDIUM",
        timeLimitMinutes: null,
        cqParts: parts,
      };
    });

  return questions.length > 0 ? questions : null;
}

const QUESTION_START = /^\s*(?:(?:Q|Question)\s*)?(\d{1,3})(?:[.)\]:-]\s*|\s+)(.*)$/i;
const QUESTION_LABEL_ONLY = /^\s*(?:Q|Question)\s*\d{1,3}\s*$/i;
const OPTION_START = /^\s*\(?([a-hA-H1-8])[.)\]:-]\s+(.*)$/;
// Matches multiple "A. ... B. ..." markers on the same line (common in
// two-column question papers where options are laid out side by side).
const INLINE_OPTION_MARKERS = /(?:^|\s)([a-hA-H])[.)\]:-]\s+/g;

function splitInlineOptions(line: string): string[] | null {
  const markers = [...line.matchAll(INLINE_OPTION_MARKERS)];
  if (markers.length < 2) return null;
  return markers
    .map((marker, index) => {
      const start = (marker.index ?? 0) + marker[0].length;
      const end = markers[index + 1]?.index ?? line.length;
      return line.slice(start, end).trim();
    })
    .filter(Boolean);
}
const MARKS_INLINE = /[\[(]\s*(\d{1,3})\s*(?:marks?|mks?)?\s*[\])]/i;
const MARKS_TRAILING = /(\d{1,3})\s*marks?\s*$/i;
const ANSWER_LINE = /^\s*(?:ans(?:wer)?|correct\s*answer)\s*[:.\-]?\s*(.+)$/i;
const MARKS_LINE = /^\s*marks?\s*[:.\-]?\s*(\d{1,3})\s*$/i;
const TIME_LINE = /^\s*time\s*[:.\-]?\s*(\d{1,3})\s*(?:minutes?|mins?)?\s*$/i;
const DIFFICULTY_LINE = /^\s*difficulty\s*[:.\-]?\s*(easy|medium|hard)\s*$/i;
const BLOCK_START = /^\s*#{0,3}\s*QUESTION_START\s*#{0,3}\s*$/i;
const BLOCK_END = /^\s*#{0,3}\s*QUESTION_END\s*#{0,3}\s*$/i;

interface RawQuestion {
  prompt: string;
  options: string[];
  marks: number | null;
  timeLimitMinutes: number | null;
  difficulty: DifficultyValue | null;
  answerHint: string | null;
}

function optionLetterIndex(token: string): number {
  const ch = token.trim().toLowerCase();
  if (ch >= "a" && ch <= "h") return ch.charCodeAt(0) - 97;
  const n = Number(ch);
  if (Number.isFinite(n) && n >= 1) return n - 1;
  return -1;
}

function normalizeDifficulty(value: unknown): DifficultyValue {
  const normalized = String(value ?? "Medium").trim().toUpperCase();
  if (normalized === "EASY" || normalized === "HARD") return normalized;
  return "MEDIUM";
}

function cleanAnswerHint(value: string) {
  return value.trim().replace(/^["']|["']$/g, "");
}

function resolveCorrectAnswer(
  answerHint: string | null,
  options: string[],
): string | null {
  if (!answerHint) return null;

  const hint = cleanAnswerHint(answerHint);
  if (options.length >= 2) {
    const idx = optionLetterIndex(hint.split(/[\s.)]/)[0] ?? "");
    if (idx >= 0 && idx < options.length) return options[idx];

    const matched = options.find(
      (option) => option.toLowerCase() === hint.toLowerCase(),
    );
    return matched ?? hint;
  }

  return hint;
}

function normalizeQuestionFromJson(input: unknown): AdminExtractedQuestion | null {
  const item = input as {
    question?: unknown;
    options?: unknown;
    correctAnswer?: unknown;
    answer?: unknown;
    marks?: unknown;
    time?: unknown;
    timeLimitMinutes?: unknown;
    difficulty?: unknown;
  };

  if (!item || typeof item !== "object" || !String(item.question ?? "").trim()) {
    return null;
  }

  const options = Array.isArray(item.options)
    ? item.options.map((option) => String(option ?? "").trim()).filter(Boolean)
    : item.options && typeof item.options === "object"
      ? ["A", "B", "C", "D"]
          .map((key) => String((item.options as Record<string, unknown>)[key] ?? "").trim())
          .filter(Boolean)
      : [];

  return {
    type: options.length >= 2 ? "MCQ" : "WRITTEN",
    question: String(item.question).trim(),
    marks: Number(item.marks) || 5,
    options,
    correctAnswer: resolveCorrectAnswer(
      item.correctAnswer === null
        ? null
        : String(item.correctAnswer ?? item.answer ?? "").trim() || null,
      options,
    ),
    rubric: null,
    difficulty: normalizeDifficulty(item.difficulty),
    timeLimitMinutes: Number(item.timeLimitMinutes ?? item.time) || 2,
  };
}

function parseJsonQuestions(text: string): AdminExtractedQuestion[] | null {
  try {
    const parsed = JSON.parse(text) as { questions?: unknown } | unknown[];
    const items = Array.isArray(parsed)
      ? parsed
      : Array.isArray((parsed as { questions?: unknown }).questions)
        ? (parsed as { questions: unknown[] }).questions
        : null;

    if (!items) return null;

    return items
      .map(normalizeQuestionFromJson)
      .filter((question): question is AdminExtractedQuestion => Boolean(question));
  } catch {
    return null;
  }
}

function finalize(raw: RawQuestion): AdminExtractedQuestion {
  const isMcq = raw.options.length >= 2;
  const type: QuestionTypeValue = isMcq ? "MCQ" : "WRITTEN";

  return {
    type,
    question: raw.prompt.trim(),
    marks: raw.marks ?? 5,
    options: raw.options,
    correctAnswer: resolveCorrectAnswer(raw.answerHint, raw.options),
    rubric: null,
    difficulty: raw.difficulty ?? "MEDIUM",
    timeLimitMinutes: raw.timeLimitMinutes ?? 2,
  };
}

function createEmptyQuestion(): RawQuestion {
  return {
    prompt: "",
    options: [],
    marks: null,
    timeLimitMinutes: null,
    difficulty: null,
    answerHint: null,
  };
}

/**
 * Force parsed questions to match the assessment's question type.
 * WRITTEN/PRACTICAL assessments drop MCQ options and answers so stray
 * option-like lines in OCR text don't turn questions into MCQs.
 */
export function coerceQuestionsToType(
  questions: AdminExtractedQuestion[],
  type: QuestionTypeValue,
): AdminExtractedQuestion[] {
  if (type !== "WRITTEN" && type !== "PRACTICAL") return questions;
  return questions.map((question) => ({
    ...question,
    type,
    options: [],
    correctAnswer: null,
    rubric: null,
  }));
}

/**
 * Parse plain text into structured questions. Fully local - no network.
 */
export function parseQuestionsFromText(text: string): AdminExtractedQuestion[] {
  const jsonQuestions = parseJsonQuestions(text.trim());
  if (jsonQuestions) return jsonQuestions;

  const cqQuestions = parseCqBlocks(text);
  if (cqQuestions) return cqQuestions;

  const lines = text
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.replace(/\u00a0/g, " ").trimEnd());

  // When the document uses ###QUESTION_START###/###QUESTION_END### markers,
  // any text before the first marker (e.g. a paper heading) is not a question.
  const usesMarkers = lines.some((line) => BLOCK_START.test(line.trim()));

  const questions: RawQuestion[] = [];
  let current: RawQuestion | null = null;
  let insideBlock = !usesMarkers;

  const push = () => {
    if (current && current.prompt.trim()) questions.push(current);
    current = null;
  };

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (BLOCK_START.test(trimmed)) {
      // Drop any pending pre-marker heading, then open a fresh block.
      current = null;
      insideBlock = true;
      continue;
    }

    if (BLOCK_END.test(trimmed)) {
      push();
      insideBlock = false;
      continue;
    }

    // Ignore stray lines that appear between blocks (headings, page numbers).
    if (!insideBlock) continue;

    const answerMatch = trimmed.match(ANSWER_LINE);
    if (answerMatch && current) {
      current.answerHint = answerMatch[1].trim();
      continue;
    }

    const marksLineMatch = trimmed.match(MARKS_LINE);
    if (marksLineMatch && current) {
      current.marks = Number(marksLineMatch[1]);
      continue;
    }

    const timeLineMatch = trimmed.match(TIME_LINE);
    if (timeLineMatch && current) {
      current.timeLimitMinutes = Number(timeLineMatch[1]);
      continue;
    }

    const difficultyLineMatch = trimmed.match(DIFFICULTY_LINE);
    if (difficultyLineMatch && current) {
      current.difficulty = normalizeDifficulty(difficultyLineMatch[1]);
      continue;
    }

    if (QUESTION_LABEL_ONLY.test(trimmed)) {
      push();
      current = createEmptyQuestion();
      continue;
    }

    const qMatch = trimmed.match(QUESTION_START);
    if (qMatch) {
      push();
      let prompt = qMatch[2].trim();
      let marks: number | null = null;
      const marksMatch = prompt.match(MARKS_INLINE) ?? prompt.match(MARKS_TRAILING);
      if (marksMatch) {
        marks = Number(marksMatch[1]);
        prompt = prompt.replace(marksMatch[0], "").trim();
      }
      current = { ...createEmptyQuestion(), prompt, marks };
      continue;
    }

    const oMatch = trimmed.match(OPTION_START);
    if (oMatch && current) {
      const inlineOptions = splitInlineOptions(trimmed);
      if (inlineOptions) {
        current.options.push(...inlineOptions);
      } else {
        current.options.push(oMatch[2].trim());
      }
      continue;
    }

    if (current) {
      if (current.options.length > 0) {
        current.options[current.options.length - 1] += " " + trimmed;
      } else {
        current.prompt = [current.prompt, trimmed].filter(Boolean).join(" ");
      }
    } else {
      current = { ...createEmptyQuestion(), prompt: trimmed };
    }
  }

  push();

  return questions.map(finalize);
}
