import type {
  AdminExtractedCqPart,
  AdminExtractedQuestion,
  DifficultyValue,
  QuestionTypeValue,
} from "@/lib/admin-assessment-types";

// Local (no-API) heuristic parser: turns OCR/AI question text into structured
// questions. Supports marker blocks, "Question 1" blocks, MCQ options,
// metadata lines, inline marks, JSON generated by an AI/OCR step,
// and multiple correct MCQ answers.

// CQ (creative question) blocks: a Bengali heading ("সৃজনশীল প্রশ্ন ১" or a
// plain "১." / "1." number), a passage (উদ্দীপক), then zero or more
// Bengali/English labeled sub-questions, each optionally ending with marks.
const CQ_HEADING =
  /^\s*(?:সৃজনশীল\s*প্রশ্ন|CQ|Creative\s*Question)\s*[-.:।]?\s*(\d{1,3}|[০-৯]{1,3})?\s*[:.।]?\s*(.*)$/iu;

const CQ_PART_START = /^\s*([ক-হ]|[A-Z])\s*[.)।:-]\s*(.*)$/iu;

const BENGALI_CQ_LABEL = /^[ক-হ]$/u;

const BENGALI_DIGIT_MAP: Record<string, string> = {
  "০": "0",
  "১": "1",
  "২": "2",
  "৩": "3",
  "৪": "4",
  "৫": "5",
  "৬": "6",
  "৭": "7",
  "৮": "8",
  "৯": "9",
};

function toArabicDigits(value: string): string {
  return value.replace(/[০-৯]/g, (ch) => BENGALI_DIGIT_MAP[ch] ?? ch);
}

const MARKS_INLINE = /[\[(]\s*(\d{1,3})\s*(?:marks?|mks?)?\s*[\])]/i;

const MARKS_TRAILING = /(\d{1,3})\s*marks?\s*$/i;

function extractTrailingMarks(text: string): {
  text: string;
  marks: number;
} {
  const match = text.match(MARKS_INLINE) ?? text.match(MARKS_TRAILING);

  if (!match) {
    return {
      text: text.trim(),
      marks: 0,
    };
  }

  const digits = toArabicDigits(match[1] ?? "");
  const marks = Number(digits) || 0;

  return {
    text: text.replace(match[0], "").trim(),
    marks,
  };
}

/**
 * Detect and parse CQ blocks (উদ্দীপক + ক/খ/গ/ঘ).
 * Returns null if the text has no CQ part markers,
 * so callers can fall back to the generic parser.
 */
function parseCqBlocks(text: string): AdminExtractedQuestion[] | null {
  const lines = text
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.replace(/ /g, " ").trim())
    .filter(Boolean);

  const partLines = lines
    .map((line) => ({
      line,
      match: line.match(CQ_PART_START),
    }))
    .filter(
      (
        item,
      ): item is {
        line: string;
        match: RegExpMatchArray;
      } => Boolean(item.match),
    );

  const hasBengaliPart = partLines.some((item) =>
    BENGALI_CQ_LABEL.test(item.match[1]),
  );

  const hasCqHeading = lines.some((line) => CQ_HEADING.test(line));

  const hasMarkedEnglishPart = partLines.some(
    (item) => MARKS_INLINE.test(item.line) || MARKS_TRAILING.test(item.line),
  );

  // Do not mistake ordinary A-D MCQ options for written sub-questions.
  if (!hasBengaliPart && !hasCqHeading && !hasMarkedEnglishPart) {
    return null;
  }

  interface CqBlock {
    passage: string[];
    parts: {
      label: string;
      lines: string[];
    }[];
  }

  const blocks: CqBlock[] = [];

  let current: CqBlock = {
    passage: [],
    parts: [],
  };

  let currentPart: {
    label: string;
    lines: string[];
  } | null = null;

  let started = false;

  const startBlock = () => {
    current = {
      passage: [],
      parts: [],
    };

    currentPart = null;
    started = true;

    blocks.push(current);
  };

  for (const line of lines) {
    const headingMatch = line.match(CQ_HEADING);

    if (headingMatch) {
      startBlock();

      const inlinePassage = (headingMatch[2] ?? "").trim();

      if (inlinePassage) {
        current.passage.push(inlinePassage);
      }

      continue;
    }

    const partMatch = line.match(CQ_PART_START);

    if (partMatch) {
      if (!started) {
        startBlock();
      }

      currentPart = {
        label: partMatch[1],
        lines: [partMatch[2]],
      };

      current.parts.push(currentPart);

      continue;
    }

    if (!started) {
      startBlock();
    }

    if (currentPart) {
      currentPart.lines.push(line);
    } else {
      current.passage.push(line);
    }
  }

  const questions = blocks
    .filter((block) => block.parts.length > 0)
    .map((block): AdminExtractedQuestion => {
      const passage = block.passage.join(" ").replace(/\s+/g, " ").trim();

      const parts: AdminExtractedCqPart[] = block.parts.map((part) => {
        const joined = part.lines.join(" ").replace(/\s+/g, " ").trim();

        const { text: partText, marks } = extractTrailingMarks(joined);

        return {
          label: part.label,
          text: partText,
          marks,
        };
      });

      const totalMarks = parts.reduce((sum, part) => sum + part.marks, 0);

      return {
        type: "WRITTEN",
        question: passage,
        marks: totalMarks,
        options: [],

        correctAnswer: null,
        correctAnswers: [],

        rubric: null,
        difficulty: "MEDIUM",
        timeLimitMinutes: null,
        cqParts: parts,
      };
    });

  return questions.length > 0 ? questions : null;
}

const QUESTION_START =
  /^\s*(?:(?:Q|Question)\s*)?(\d{1,3})(?:[.)\]:-]\s*|\s+)(.*)$/i;

const QUESTION_LABEL_ONLY = /^\s*(?:Q|Question)\s*\d{1,3}\s*$/i;

const OPTION_START = /^\s*\(?([a-hA-H1-8])[.)\]:-]\s+(.*)$/;

const INLINE_OPTION_MARKERS = /(?:^|\s)([a-hA-H])[.)\]:-]\s+/g;

function splitInlineOptions(line: string): string[] | null {
  const markers = [...line.matchAll(INLINE_OPTION_MARKERS)];

  if (markers.length < 2) {
    return null;
  }

  return markers
    .map((marker, index) => {
      const start = (marker.index ?? 0) + marker[0].length;

      const end = markers[index + 1]?.index ?? line.length;

      return line.slice(start, end).trim();
    })
    .filter(Boolean);
}

const ANSWER_LINE = /^\s*(?:ans(?:wer)?|correct\s*answer)\s*[:.\-]?\s*(.+)$/i;

const MARKS_LINE = /^\s*marks?\s*[:.\-]?\s*(\d{1,3})\s*$/i;

const TIME_LINE = /^\s*time\s*[:.\-]?\s*(\d{1,3})\s*(?:minutes?|mins?)?\s*$/i;

const DIFFICULTY_LINE = /^\s*difficulty\s*[:.\-]?\s*(easy|medium|hard)\s*$/i;

const BLOCK_START = /^\s*#{0,3}\s*QUESTION_START\s*#{0,3}\s*$/i;

const BLOCK_END = /^\s*#{0,3}\s*QUESTION_END\s*#{0,3}\s*$/i;

interface RawQuestion {
  prompt: string;
  options: string[];
  marks: number | null;
  timeLimitMinutes: number | null;
  difficulty: DifficultyValue | null;
  answerHint: string | null;
}

function optionLetterIndex(token: string): number {
  const ch = token.trim().toLowerCase();

  if (ch >= "a" && ch <= "h") {
    return ch.charCodeAt(0) - 97;
  }

  const n = Number(ch);

  if (Number.isFinite(n) && n >= 1) {
    return n - 1;
  }

  return -1;
}

function normalizeDifficulty(value: unknown): DifficultyValue {
  const normalized = String(value ?? "Medium")
    .trim()
    .toUpperCase();

  if (normalized === "EASY" || normalized === "HARD") {
    return normalized;
  }

  return "MEDIUM";
}

function cleanAnswerHint(value: string) {
  return value.trim().replace(/^["']|["']$/g, "");
}

/**
 * Resolve one or multiple MCQ answers.
 *
 * Supported:
 *
 * Answer: A
 * Answer: A, B
 * Answer: A, B, D
 * Answer: A,B,C,D
 * Answer: A B D
 * Answer: A & C
 * Answer: A and C
 * Answer: 1, 3
 */
function resolveCorrectAnswers(
  answerHint: string | null,
  options: string[],
): string[] {
  if (!answerHint || options.length === 0) {
    return [];
  }

  const hint = cleanAnswerHint(answerHint);

  const tokens = hint
    .split(/\s*(?:,|;|&|\band\b)\s*|\s+/i)
    .map((token) => token.replace(/[()[\].:]/g, "").trim())
    .filter(Boolean);

  const resolved: string[] = [];

  for (const token of tokens) {
    const index = optionLetterIndex(token);

    if (index >= 0 && index < options.length) {
      const option = options[index];

      if (!resolved.includes(option)) {
        resolved.push(option);
      }

      continue;
    }

    const matchedOption = options.find(
      (option) => option.toLowerCase().trim() === token.toLowerCase().trim(),
    );

    if (matchedOption && !resolved.includes(matchedOption)) {
      resolved.push(matchedOption);
    }
  }

  // Also support full option text.
  // Example:
  // Answer: Rabindranath Tagore
  if (resolved.length === 0) {
    const matchedOption = options.find(
      (option) => option.toLowerCase().trim() === hint.toLowerCase().trim(),
    );

    if (matchedOption) {
      resolved.push(matchedOption);
    }
  }

  return resolved;
}

/**
 * Backward compatibility:
 * correctAnswer stores the first correct option.
 */
function resolveCorrectAnswer(
  answerHint: string | null,
  options: string[],
): string | null {
  return resolveCorrectAnswers(answerHint, options)[0] ?? null;
}

function normalizeQuestionFromJson(
  input: unknown,
): AdminExtractedQuestion | null {
  const item = input as {
    question?: unknown;
    options?: unknown;

    correctAnswer?: unknown;
    correctAnswers?: unknown;

    answer?: unknown;

    marks?: unknown;

    time?: unknown;

    timeLimitMinutes?: unknown;

    difficulty?: unknown;

    cqParts?: unknown;
  };

  if (
    !item ||
    typeof item !== "object" ||
    !String(item.question ?? "").trim()
  ) {
    return null;
  }

  const options = Array.isArray(item.options)
    ? item.options.map((option) => String(option ?? "").trim()).filter(Boolean)
    : item.options && typeof item.options === "object"
      ? ["A", "B", "C", "D"]
          .map((key) =>
            String((item.options as Record<string, unknown>)[key] ?? "").trim(),
          )
          .filter(Boolean)
      : [];

  const cqParts = Array.isArray(item.cqParts)
    ? item.cqParts
        .map((part, index) => {
          const value = part as {
            label?: unknown;
            text?: unknown;
            question?: unknown;
            marks?: unknown;
          };

          const text = String(value?.text ?? value?.question ?? "").trim();

          if (!text) {
            return null;
          }

          return {
            label: String(value?.label ?? String.fromCharCode(65 + index)),
            text,
            marks: Math.max(0, Number(value?.marks) || 0),
          } satisfies AdminExtractedCqPart;
        })
        .filter((part): part is AdminExtractedCqPart => Boolean(part))
    : [];

  const cqMarks = cqParts.reduce((sum, part) => sum + part.marks, 0);

  let correctAnswers: string[] = [];

  /*
   * JSON can provide:
   *
   * correctAnswers: ["A", "C"]
   *
   * OR
   *
   * correctAnswer: "A, C"
   *
   * OR
   *
   * answer: "A, C"
   */
  if (Array.isArray(item.correctAnswers)) {
    const answers = item.correctAnswers
      .map((answer) => String(answer ?? "").trim())
      .filter(Boolean);

    const resolved = new Set<string>();

    for (const answer of answers) {
      const result = resolveCorrectAnswers(answer, options);

      result.forEach((value) => resolved.add(value));
    }

    correctAnswers = [...resolved];
  } else {
    const answerHint =
      item.correctAnswer === null
        ? null
        : String(item.correctAnswer ?? item.answer ?? "").trim() || null;

    correctAnswers = resolveCorrectAnswers(answerHint, options);
  }

  return {
    type: options.length >= 2 ? "MCQ" : "WRITTEN",

    question: String(item.question).trim(),

    marks: cqParts.length > 0 ? cqMarks : Number(item.marks) || 5,

    options,

    // Backward compatibility.
    correctAnswer: correctAnswers[0] ?? null,

    // Actual multiple answers.
    correctAnswers,

    rubric: null,

    difficulty: normalizeDifficulty(item.difficulty),

    timeLimitMinutes: Number(item.timeLimitMinutes ?? item.time) || 2,

    ...(cqParts.length > 0
      ? {
          cqParts,
        }
      : {}),
  };
}

function parseJsonQuestions(text: string): AdminExtractedQuestion[] | null {
  try {
    const parsed = JSON.parse(text) as
      | {
          questions?: unknown;
        }
      | unknown[];

    const items = Array.isArray(parsed)
      ? parsed
      : Array.isArray(
            (
              parsed as {
                questions?: unknown;
              }
            ).questions,
          )
        ? (
            parsed as {
              questions: unknown[];
            }
          ).questions
        : null;

    if (!items) {
      return null;
    }

    return items
      .map(normalizeQuestionFromJson)
      .filter((question): question is AdminExtractedQuestion =>
        Boolean(question),
      );
  } catch {
    return null;
  }
}

function finalize(raw: RawQuestion): AdminExtractedQuestion {
  const isMcq = raw.options.length >= 2;

  const type: QuestionTypeValue = isMcq ? "MCQ" : "WRITTEN";

  const correctAnswers = isMcq
    ? resolveCorrectAnswers(raw.answerHint, raw.options)
    : [];

  return {
    type,

    question: raw.prompt.trim(),

    marks: raw.marks ?? 5,

    options: raw.options,

    // Keep first answer for old parts
    // of the LMS that still use
    // correctAnswer.
    correctAnswer: correctAnswers[0] ?? null,

    // New multiple-answer support.
    correctAnswers,

    rubric: null,

    difficulty: raw.difficulty ?? "MEDIUM",

    timeLimitMinutes: raw.timeLimitMinutes ?? 2,
  };
}

function createEmptyQuestion(): RawQuestion {
  return {
    prompt: "",
    options: [],
    marks: null,
    timeLimitMinutes: null,
    difficulty: null,
    answerHint: null,
  };
}

/**
 * Force parsed questions to match the
 * assessment question type.
 *
 * WRITTEN / PRACTICAL assessments
 * must never retain MCQ answers.
 */
export function coerceQuestionsToType(
  questions: AdminExtractedQuestion[],
  type: QuestionTypeValue,
): AdminExtractedQuestion[] {
  if (type !== "WRITTEN" && type !== "PRACTICAL") {
    return questions;
  }

  return questions.map((question) => ({
    ...question,

    type,

    options: [],

    correctAnswer: null,

    correctAnswers: [],

    rubric: null,
  }));
}

/**
 * Parse plain text into structured
 * questions.
 *
 * Fully local — no network/API.
 */
export function parseQuestionsFromText(text: string): AdminExtractedQuestion[] {
  const jsonQuestions = parseJsonQuestions(text.trim());

  if (jsonQuestions) {
    return jsonQuestions;
  }

  const cqQuestions = parseCqBlocks(text);

  if (cqQuestions) {
    return cqQuestions;
  }

  const lines = text
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.replace(/\u00a0/g, " ").trimEnd());

  // If markers exist, anything outside
  // QUESTION_START / QUESTION_END is ignored.
  const usesMarkers = lines.some((line) => BLOCK_START.test(line.trim()));

  const questions: RawQuestion[] = [];

  let current: RawQuestion | null = null;

  let insideBlock = !usesMarkers;

  const push = () => {
    if (current && current.prompt.trim()) {
      questions.push(current);
    }

    current = null;
  };

  for (const line of lines) {
    const trimmed = line.trim();

    if (!trimmed) {
      continue;
    }

    if (BLOCK_START.test(trimmed)) {
      // Drop pending text before
      // the marker.
      current = null;

      insideBlock = true;

      continue;
    }

    if (BLOCK_END.test(trimmed)) {
      push();

      insideBlock = false;

      continue;
    }

    if (!insideBlock) {
      continue;
    }

    /*
     * ANSWER
     *
     * Supports:
     *
     * Answer: A
     * Answer: A, B
     * Answer: A, C, D
     * Answer: A B D
     */
    const answerMatch = trimmed.match(ANSWER_LINE);

    if (answerMatch && current) {
      current.answerHint = answerMatch[1].trim();

      continue;
    }

    /*
     * MARKS
     */
    const marksLineMatch = trimmed.match(MARKS_LINE);

    if (marksLineMatch && current) {
      current.marks = Number(marksLineMatch[1]);

      continue;
    }

    /*
     * TIME
     */
    const timeLineMatch = trimmed.match(TIME_LINE);

    if (timeLineMatch && current) {
      current.timeLimitMinutes = Number(timeLineMatch[1]);

      continue;
    }

    /*
     * DIFFICULTY
     */
    const difficultyLineMatch = trimmed.match(DIFFICULTY_LINE);

    if (difficultyLineMatch && current) {
      current.difficulty = normalizeDifficulty(difficultyLineMatch[1]);

      continue;
    }

    /*
     * Question 1
     *
     * with question text
     * on the following line.
     */
    if (QUESTION_LABEL_ONLY.test(trimmed)) {
      push();

      current = createEmptyQuestion();

      continue;
    }

    /*
     * Question 1 What is AI?
     *
     * or:
     *
     * 1. What is AI?
     */
    const qMatch = trimmed.match(QUESTION_START);

    if (qMatch) {
      push();

      let prompt = qMatch[2].trim();

      let marks: number | null = null;

      const marksMatch =
        prompt.match(MARKS_INLINE) ?? prompt.match(MARKS_TRAILING);

      if (marksMatch) {
        marks = Number(marksMatch[1]);

        prompt = prompt.replace(marksMatch[0], "").trim();
      }

      current = {
        ...createEmptyQuestion(),

        prompt,

        marks,
      };

      continue;
    }

    /*
     * Options
     *
     * A. Option
     * B. Option
     *
     * Also supports inline:
     *
     * A. First B. Second
     */
    const oMatch = trimmed.match(OPTION_START);

    if (oMatch && current) {
      const inlineOptions = splitInlineOptions(trimmed);

      if (inlineOptions) {
        current.options.push(...inlineOptions);
      } else {
        current.options.push(oMatch[2].trim());
      }

      continue;
    }

    /*
     * Continuation lines.
     */
    if (current) {
      if (current.options.length > 0) {
        current.options[current.options.length - 1] += ` ${trimmed}`;
      } else {
        current.prompt = [current.prompt, trimmed].filter(Boolean).join(" ");
      }
    } else {
      current = {
        ...createEmptyQuestion(),

        prompt: trimmed,
      };
    }
  }

  push();

  return questions.map(finalize);
}
