import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/public/LegalPage";

export const metadata: Metadata = { title: "Terms of Service | BOED LMS", description: "Terms governing access to and use of the BOED learning management platform." };

const sections: LegalSection[] = [
  { title: "Acceptance of these terms", paragraphs: ["By accessing or using BOED LMS, you agree to these Terms of Service and any policies referenced here. If an institution provides your access, its agreement with BOED may also govern your use. If you do not agree, do not use the service."] },
  { title: "Accounts and eligibility", paragraphs: ["You must provide accurate information, keep your credentials confidential, and promptly report suspected unauthorized access. You are responsible for activity performed through your account unless applicable law provides otherwise."], items: ["Use only the account assigned to you.", "Do not share passwords or bypass access controls.", "Keep account and enrollment details reasonably current.", "Use the service only where you are legally able to enter this agreement or have proper authorization."] },
  { title: "Acceptable use", paragraphs: ["You may use BOED LMS for legitimate education, training, administration, and related activities."], items: ["Do not disrupt, overload, probe, or attempt unauthorized access to the platform.", "Do not upload malware, unlawful material, or content that infringes another person’s rights.", "Do not cheat, impersonate another learner, falsify attendance, or manipulate assessments or credentials.", "Do not scrape, resell, reverse engineer, or misuse platform data except where law expressly permits it."] },
  { title: "Courses and enrollment", paragraphs: ["Course availability, admission decisions, schedules, assessment rules, completion requirements, and any fees are set by BOED or the institution providing the course. Enrollment requests may require review and are not guaranteed to be approved."] },
  { title: "Content and intellectual property", paragraphs: ["BOED LMS and its software, branding, design, and platform materials are protected by applicable intellectual-property laws. Course creators and institutions retain rights in their materials. You receive a limited, personal, non-transferable right to access authorized content for learning purposes."], items: ["You retain ownership of content you submit.", "You grant BOED and the responsible institution permission to host, process, and display submitted content as needed to operate the service.", "You must have the rights needed for anything you upload."] },
  { title: "Assessments and certificates", paragraphs: ["Results and certificates depend on meeting the requirements established for a course. Suspected misconduct, administrative error, or later-discovered ineligibility may result in review, correction, suspension, or revocation. Public verification confirms the current status recorded by BOED LMS; it does not replace independent due diligence."] },
  { title: "Service availability", paragraphs: ["We work to keep BOED LMS reliable, but uninterrupted or error-free access is not guaranteed. Features may change, and access may be temporarily limited for maintenance, security, legal, or operational reasons."] },
  { title: "Suspension and termination", paragraphs: ["Access may be limited or terminated if these terms are breached, an institution withdraws access, a course ends, payment obligations are not met, or action is reasonably needed to protect users or the platform. Provisions that should logically continue after termination will survive."] },
  { title: "Disclaimers and liability", paragraphs: ["To the extent permitted by law, the service is provided on an “as available” basis. BOED does not promise that completing a course will lead to employment, licensing, admission, or a particular professional result. Liability is limited to the greatest extent permitted by applicable law; nothing here excludes rights or liabilities that cannot legally be excluded."] },
  { title: "Changes and contact", paragraphs: ["We may update these terms to reflect changes to the service or applicable requirements. Continued use after an update takes effect constitutes acceptance where permitted by law. Questions may be sent to mailer@boed.org."] },
];

export default function TermsPage() {
  return <LegalPage title="Terms of Service" description="These terms set the ground rules for using BOED LMS responsibly and safely." updated="September 10, 2026" sections={sections} />;
}
